version: '3'

services:
  nginx:
    image: nginx:1.13.9-alpine
    container_name: nginx
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  schemaspy:
    build: ./schemaspy
    container_name: schemaspy
    volumes:
      - ./app:/app/html:rw
      - ./schemaspy/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    working_dir: "/app"
    command: "java -jar schemaspy.jar -all"

  db:
    build: ./psql
    container_name: psql
    volumes:
      - schema_spy-playground-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=spy
      - POSTGRES_PASSWORD=spy
      - POSTGRES_DB=schema_spy

volumes:
  schema_spy-playground-db:
    driver: local
